environment:
  nodejs_version: "20" # окружение

branches:
  only:
    - main
    - master  # ветка git

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
